version: '3.7'

services:
  api:
    image: swanbay-api-dev
    container_name: swanbay-api-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "8005:8005"
    restart: on-failure
    tty: true
    networks:
      - db
networks:
  db:
    external: true
