version: '3.7'

services:
  mongo:
    image: mongo:5.0.6-focal
    container_name: swanbay-mongo-dev
    restart: always
    volumes:
      - /db/mongodb:/data/db
    networks:
      - db
    ports:
      - 27017:27017

networks:
  db:
    external: true
